/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaMVCViews;

import JavaMVCControllers.InventoryController;
import java.awt.Component;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.EventListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;

/**
 *
 * @author Stephen
 */
public class InventoryView extends javax.swing.JFrame {
    public InventoryController Controller = new InventoryController();
    private DefaultTableModel DefaultTableModel;

    /**
     * Creates new form InventoryView
     */
    public InventoryView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SaleTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        idBox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        QuantityBox = new javax.swing.JTextField();
        AddProdBtn = new javax.swing.JButton();
        RemoveProdBtn = new javax.swing.JButton();
        CompleteSaleBtn = new javax.swing.JButton();
        WarningLabel = new javax.swing.JLabel();
        SubBox = new javax.swing.JTextField();
        TotBox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MovementList = new javax.swing.JList<>();
        ShelfAmtLabel = new javax.swing.JLabel();
        BackAmtLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AmtToOrder = new javax.swing.JTextField();
        OrderBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PiecesMovedBox = new javax.swing.JTextField();
        MoveObjectsButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        EmptyShelfLabel = new javax.swing.JLabel();
        PerCaseLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UpID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UpDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UpPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        UpShelfSpace = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        UpCaseSize = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UpShelf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UpBack = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        EditProdBtn = new javax.swing.JButton();
        CreateProdBtn = new javax.swing.JButton();
        UpdateWarningLabel = new javax.swing.JLabel();
        DelProdBtn = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        SaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(SaleTable);

        jLabel14.setText("Insert Product ID or Description:");

        jLabel15.setText("Quantity:");

        QuantityBox.setText("1");

        AddProdBtn.setText("Add Product");
        AddProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProdBtnActionPerformed(evt);
            }
        });

        RemoveProdBtn.setText("Delete Product");

        CompleteSaleBtn.setText("Complete Sale");
        CompleteSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteSaleBtnActionPerformed(evt);
            }
        });

        WarningLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WarningLabel.setText("Warning Label:");

        jLabel17.setText("Subtotal:");

        jLabel18.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(idBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(QuantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CompleteSaleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddProdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(WarningLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(RemoveProdBtn)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotBox, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(SubBox))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddProdBtn)
                            .addComponent(RemoveProdBtn))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(QuantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(WarningLabel)
                                    .addComponent(CompleteSaleBtn)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sales", jPanel1);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Number", "Description", "Price", "Number on Shelf", "Number in Back"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ProductTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ProductList", jPanel2);

        MovementList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MovementListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(MovementList);

        ShelfAmtLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ShelfAmtLabel.setText("Number On Shelf:");

        BackAmtLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BackAmtLabel.setText("Number in Back:");

        jLabel9.setText("Select an item from the list:");

        AmtToOrder.setText("1");

        OrderBtn.setText("Complete Order");
        OrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Cases Recieved:");

        jLabel11.setText("This section is to move products from backstock to the shelf:");

        jLabel12.setText("Pieces Moved:");

        MoveObjectsButton.setText("Move Products");
        MoveObjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveObjectsButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("This section tells the program when a shipment is recieved:");

        EmptyShelfLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EmptyShelfLabel.setText("Empty Shelf Space:");

        PerCaseLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PerCaseLabel.setText("Pieces per Case:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BackAmtLabel)
                            .addComponent(ShelfAmtLabel)
                            .addComponent(EmptyShelfLabel)
                            .addComponent(PerCaseLabel))
                        .addGap(219, 219, 219))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(AmtToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(112, 112, 112)
                                                .addComponent(OrderBtn))
                                            .addComponent(jLabel10))))
                                .addGap(64, 64, 64))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addComponent(jLabel12))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(PiecesMovedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(121, 121, 121)
                                            .addComponent(MoveObjectsButton)))
                                    .addGap(75, 75, 75))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ShelfAmtLabel)
                        .addGap(18, 18, 18)
                        .addComponent(BackAmtLabel)
                        .addGap(18, 18, 18)
                        .addComponent(EmptyShelfLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PerCaseLabel)
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PiecesMovedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MoveObjectsButton))
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AmtToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderBtn))
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Product Movement", jPanel3);

        jLabel2.setText("Product ID:");

        jLabel3.setText("Product Description:");

        jLabel4.setText("Price:");

        jLabel5.setText("Available Shelf Space:");

        jLabel6.setText("Pieces per Case:");

        UpCaseSize.setText("12");

        jLabel7.setText("Pieces on Shelf:");

        UpShelf.setText("0");

        jLabel8.setText("Pieces in BackStock:");

        UpBack.setText("0");

        ProductList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ProductList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ProductListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ProductList);

        EditProdBtn.setText("Update Product");
        EditProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdBtnActionPerformed(evt);
            }
        });

        CreateProdBtn.setText("Create Product");
        CreateProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProdBtnActionPerformed(evt);
            }
        });

        DelProdBtn.setText("Delete Product");
        DelProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelProdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpShelfSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpCaseSize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditProdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreateProdBtn)
                            .addComponent(DelProdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateWarningLabel)
                        .addGap(35, 35, 35))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(UpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpShelfSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpCaseSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(UpdateWarningLabel)
                        .addGap(73, 73, 73)
                        .addComponent(CreateProdBtn)
                        .addGap(18, 18, 18)
                        .addComponent(EditProdBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DelProdBtn)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Product Change", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(125, 167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
//set the list models to the lists when the tab is changed
ProductTable.setModel(DLM);  
ProductList.setModel(model);
MovementList.setModel(model);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void EditProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdBtnActionPerformed
//gets the selection of the list, then clears it
        int selected = ProductList.getSelectedIndex();
ProductList.clearSelection();
//makes sure something is selected
if(selected == -1){
    UpdateWarningLabel.setText("Please select a product to update from the list.");
}else{if(UpID.getText().equals("") || UpDesc.getText().equals("") || UpPrice.getText().equals("") || UpShelfSpace.getText().equals("") || UpShelf.getText().equals("") || UpBack.getText().equals("") || UpCaseSize.getText().equals("")){
          UpdateWarningLabel.setText("Please complete all feilds.");    
}else{
    try {//calls the update function in the controller script
        Controller.updateDatabase(selected, UpID.getText(), UpDesc.getText(), UpPrice.getText(), UpShelfSpace.getText(), UpShelf.getText(), UpBack.getText(), UpCaseSize.getText());
    } catch (IOException ex) {
        Logger.getLogger(InventoryView.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}}


    }//GEN-LAST:event_EditProdBtnActionPerformed

    private void ProductListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ProductListValueChanged
        // make sure a product is selected in the list, call the function productlookup
       if (ProductList.getSelectedIndex() > -1){ 
      UpdateWarningLabel.setText("");
        int selected = ProductList.getSelectedIndex();
String ProdString = Controller.lookupProduct(selected);
String[] prod = ProdString.split("`");
//split the returned string and assign the parts to the correct text feild.
UpBack.setText(prod[5]);
UpCaseSize.setText(prod[6]);
UpDesc.setText(prod[1]);
UpID.setText(prod[0]);
UpPrice.setText(prod[2]);
UpShelf.setText(prod[4]);
UpShelfSpace.setText(prod[3]);
       }
    }//GEN-LAST:event_ProductListValueChanged

    private void CreateProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProdBtnActionPerformed
int selected = -1;
//calls the updateDatabase function with a -1.. which means use the next empty array entry.
if(UpID.getText().equals("") || UpDesc.getText().equals("") || UpPrice.getText().equals("") || UpShelfSpace.getText().equals("") || UpShelf.getText().equals("") || UpBack.getText().equals("") || UpCaseSize.getText().equals("")){
          UpdateWarningLabel.setText("Please complete all feilds.");
}else{
        try {
            Controller.updateDatabase(selected, UpID.getText(), UpDesc.getText(), UpPrice.getText(), UpShelfSpace.getText(), UpShelf.getText(), UpBack.getText(), UpCaseSize.getText());
        } catch (IOException ex) {
            Logger.getLogger(InventoryView.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    }//GEN-LAST:event_CreateProdBtnActionPerformed

    private void DelProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelProdBtnActionPerformed
//get the selected index, make sure one is selected call the delete product function with the selected index.
        int selected = ProductList.getSelectedIndex();
        if(selected == -1){
    UpdateWarningLabel.setText("Please select a product to update from the list.");
}else{
    try {
        Controller.deleteProduct(selected);
    } catch (IOException ex) {
        Logger.getLogger(InventoryView.class.getName()).log(Level.SEVERE, null, ex);
    }
}
        
        
    }//GEN-LAST:event_DelProdBtnActionPerformed

    private void MovementListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MovementListValueChanged

       if (MovementList.getSelectedIndex() > -1){ 

        int selected = MovementList.getSelectedIndex();
String ProdString = Controller.lookupProduct(selected);
String[] prod = ProdString.split("`");
//split the returned string and assign the parts to the correct text feild.
BackAmtLabel.setText("Number in Back: " + prod[5]);
PerCaseLabel.setText("Pieces per Case: " + prod[6]);
//UpDesc.setText(prod[1]);
//UpID.setText(prod[0]);
//UpPrice.setText(prod[2]);
ShelfAmtLabel.setText("Number on Shelf: " + prod[4]);
//UpShelfSpace.setText(prod[3]);
BackPcs = Integer.parseInt(prod[5]);
ShelfPcs = Integer.parseInt(prod[4]);
int openShelf = Integer.parseInt(prod[3]) - Integer.parseInt(prod[4]);

EmptyShelfLabel.setText("Empty Shelf Space: " + openShelf);

if(openShelf > Integer.parseInt(prod[5])){
    PiecesMovedBox.setText(prod[5]);
}else{
    PiecesMovedBox.setText(Integer.toString(openShelf));
}

       }

    }//GEN-LAST:event_MovementListValueChanged
int BackPcs;
int ShelfPcs;
NumberFormat formatter = NumberFormat.getCurrencyInstance();
    private void MoveObjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveObjectsButtonActionPerformed

        int piecesMoved = Integer.parseInt(PiecesMovedBox.getText());
        
        if(piecesMoved <= BackPcs && piecesMoved > 0 || piecesMoved * -1 <= ShelfPcs && piecesMoved < 0){
            try {
                Controller.moveBackstock(MovementList.getSelectedIndex(), PiecesMovedBox.getText());
            } catch (IOException ex) {
                Logger.getLogger(InventoryView.class.getName()).log(Level.SEVERE, null, ex);
            }
BackAmtLabel.setText("Number in Back: ");
ShelfAmtLabel.setText("Number on Shelf: ");
EmptyShelfLabel.setText("Empty Shelf Space: ");
PerCaseLabel.setText("Pieces per Case: ");
        }else{
            BackAmtLabel.setText("more pieces");
ShelfAmtLabel.setText("Cannot move");
EmptyShelfLabel.setText("than owned!!");
PerCaseLabel.setText("**********");
            
        }
    }//GEN-LAST:event_MoveObjectsButtonActionPerformed

    private void OrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtnActionPerformed
        try {
            Controller.OrderProd(MovementList.getSelectedIndex(), AmtToOrder.getText());
        } catch (IOException ex) {
            Logger.getLogger(InventoryView.class.getName()).log(Level.SEVERE, null, ex);
        }
        BackAmtLabel.setText("Number in Back: ");
ShelfAmtLabel.setText("Number on Shelf: ");
EmptyShelfLabel.setText("Empty Shelf Space: ");
PerCaseLabel.setText("Pieces per Case: ");
    }//GEN-LAST:event_OrderBtnActionPerformed

    private void AddProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProdBtnActionPerformed
Controller.addProduct(idBox.getText(), QuantityBox.getText());
SaleTable.setModel(sale);

    SubBox.setText(formatter.format(subTotal));
    TotBox.setText(formatter.format(total));
    WarningLabel.setText(warningText);
    }//GEN-LAST:event_AddProdBtnActionPerformed

    private void CompleteSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteSaleBtnActionPerformed
sale.setRowCount(0);
warningText = "Customer total is: " + total;
subTotal = 0;
total = 0;

        try {
            Controller.endSale();
        } catch (IOException ex) {
            Logger.getLogger(InventoryView.class.getName()).log(Level.SEVERE, null, ex);
        }

    WarningLabel.setText(warningText);
    SubBox.setText(formatter.format(subTotal));
    TotBox.setText(formatter.format(total));
    }//GEN-LAST:event_CompleteSaleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryView().setVisible(true);
            }
        });
        


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProdBtn;
    private javax.swing.JTextField AmtToOrder;
    private javax.swing.JLabel BackAmtLabel;
    private javax.swing.JButton CompleteSaleBtn;
    private javax.swing.JButton CreateProdBtn;
    private javax.swing.JButton DelProdBtn;
    private javax.swing.JButton EditProdBtn;
    private javax.swing.JLabel EmptyShelfLabel;
    private javax.swing.JButton MoveObjectsButton;
    private javax.swing.JList<String> MovementList;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JLabel PerCaseLabel;
    private javax.swing.JTextField PiecesMovedBox;
    private javax.swing.JList<String> ProductList;
    private javax.swing.JTable ProductTable;
    private javax.swing.JTextField QuantityBox;
    private javax.swing.JButton RemoveProdBtn;
    private javax.swing.JTable SaleTable;
    private javax.swing.JLabel ShelfAmtLabel;
    private javax.swing.JTextField SubBox;
    private javax.swing.JTextField TotBox;
    private javax.swing.JTextField UpBack;
    private javax.swing.JTextField UpCaseSize;
    private javax.swing.JTextField UpDesc;
    private javax.swing.JTextField UpID;
    private javax.swing.JTextField UpPrice;
    private javax.swing.JTextField UpShelf;
    private javax.swing.JTextField UpShelfSpace;
    private javax.swing.JLabel UpdateWarningLabel;
    private javax.swing.JLabel WarningLabel;
    private javax.swing.JTextField idBox;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
public static DefaultTableModel DLM = new DefaultTableModel();//the table on tab 2
public static DefaultListModel model = new DefaultListModel();//the list on the product change tab
public static DefaultTableModel sale = new DefaultTableModel();

    public void updateList(int id, String description, float price, int shelfAmt, int backAmt) {
//set the columns
    String [] columns = {"Product Number", "Description", "Price", "Number on Shelf", "Number in Back"};
DLM.setColumnIdentifiers(columns);

//add a row for each table.. each time the function is called    
    DLM.addRow(new Object[]{id,description,formatter.format(price),shelfAmt,backAmt});
    model.addElement(description);
    
        //System.out.println(id + description + price + shelfAmt + backAmt);

;


        }

    public void ClearLists() {
        //remove all the entries in both lists so they can be refilled
DLM.setRowCount(0);
model.clear();

    }
    static float subTotal;
    static float total;

    public void sale(int id, String description, float price, float runningTotal, float taxTotal) {
    System.out.println("view" + description + runningTotal);
    String [] columns = {"Product Number", "Description", "Price"};
    sale.setColumnIdentifiers(columns);
    sale.addRow(new Object[]{id,description,formatter.format(price)});
    subTotal = runningTotal;
    total = taxTotal;
    warningText = "";

    }
static String warningText = "";
    public void saleWarning(String warning) {
warningText = warning;
    }


    }


